- .github/workflows/run-tests.yml
- .vscode/launch.json
- .vscode/tasks.json
- messaging/AppSettings.cs
- messaging/Controllers/BundlesController.cs
- messaging/Program.cs
- messaging/Services/ConvertToIJEBackgroundWork.cs
- messaging/Startup.cs
- messaging/appsettings.Development.json
- messaging/appsettings.Test.json
By default the application will not do background processing, only when AppSettings.AckAndIJEConversion is set to true in the appropriate AppSettings.json will the app write ACK messages to the OutgoingMessageItems table and convert messages to IJE.
This PR also fixes the `.vscode/launch.json` and `.vscode/tasks.json` since they were never updated when the repo was restructured into `messaging` and `messaging.tests` folders.
> Add support for disabling all background message processing

- README.md
- messaging/Controllers/BundlesController.cs
- messaging/Migrations/20211203145846_AddMessageIdentificationInformation.Designer.cs
- messaging/Migrations/20211203145846_AddMessageIdentificationInformation.cs
- messaging/Migrations/20211207185123_AddIndexesForNCHSIdAndMessageId.Designer.cs
- messaging/Migrations/20211207185123_AddIndexesForNCHSIdAndMessageId.cs
- messaging/Migrations/20211209005127_AddIndexToOutgoingMessageItemsCreatedDate.Designer.cs
- messaging/Migrations/20211209005127_AddIndexToOutgoingMessageItemsCreatedDate.cs
- messaging/Migrations/20211210213447_AddJurisdictionIdToAllTables.Designer.cs
- messaging/Migrations/20211210213447_AddJurisdictionIdToAllTables.cs
- messaging/Models/IncomingMessageItem.cs
- messaging/Models/IncomingMessageLog.cs
- messaging/Models/OutgoingMessageItem.cs
- messaging/Services/ConvertToIJEBackgroundWork.cs
IncomingMessageItems table schema changes:
* Rename the FileSource column to Source (this will differentiate direct messages from jurisdictions from those using STEVE)
* Add a ProcessedStatus column (when NVSS API inserts the FHIR messages into the IncomingMessage table the ProcessingStatus column will be set to “QUEUED”; when the NCHS API PARSER parses the FHIR Message, it will set that column to “PROCESSED”)
OutgoingMessageItems table schema changes:
* Add a MessageType column (value is based on result of message.GetType().Name)
> Store more information about messages in the database outside of the JSON message blob

- README.md
- messaging.tests/Integration/BundlesControllerTests.cs
- messaging/Controllers/BundlesController.cs
- messaging/Models/IncomingMessageItem.cs
This adds a prefix to every route to identify which Jurisdiction ID the message is going to/coming from. The assumption is that the user validation is handled at the gateway before this code is executed. This also adds a simple test to make sure that the messages returned for a jurisdictions are contained to that jurisdiction and updates all of the README examples.
> Add support for filtering messages per Jurisdiction ID

- messaging/Controllers/BundlesController.cs
- messaging/Migrations/20220203213326_Add-Meta-Data-Columns.Designer.cs
- messaging/Migrations/20220203213326_Add-Meta-Data-Columns.cs
- messaging/Models/IncomingMessageItem.cs
- messaging/Models/OutgoingMessageItem.cs
Veronique's request:
- For the IncomingMessageItems table
- event year
- certificate number
- Event type --  values could be “ MOR” – represents death Record”, “FET “ represents Fetal Death”, “NAT” – represents Natality. 
- For OutgoingMessageItems table
- event year
- certificate number
-  Event type --  values could be either “ MOR” – represents death Record”, “FET “ represents Fetal Death”, “NAT” – represents Natality.
> Update db to store meta data

- messaging.tests/Integration/BundlesControllerTests.cs
- messaging/Controllers/BundlesController.cs
- messaging/Migrations/20220518194636_Add-RetrievedAt-Column.Designer.cs
- messaging/Migrations/20220518194636_Add-RetrievedAt-Column.cs
- messaging/Migrations/20220518195409_Make-RetrievedAt-Nullable.Designer.cs
- messaging/Migrations/20220518195409_Make-RetrievedAt-Nullable.cs
- messaging/Models/OutgoingMessageItem.cs
- messaging/Services/ConvertToIJEBackgroundWork.cs
- messaging/messaging.csproj
Updated the FHIR API to use the latest version of the library running in master
Added a RetrievedAt column to the outgoing messages table
Expected behavior defined in ticket [NVSS-325](https://tracker.codev.mitre.org/browse/NVSS-325)
- If the _since parameter is specified in the GET request, return all outgoing messages for the jurisdiction since the provided timestamp
- If the _since parameter is not provided, return all outgoing messages for the jurisdiction where RetrievedAt == null
- The RetrievedAt timestamp is updated for all messages returned in the GET request response
NOTE This PR does not include the changes to support the STEVE endpoints. This is the first iteration to test the RetrievedAt functionality and will be expanded in a future PR to support the STEVE endpoints.
> 356 v1.3 updates, add RetrievedAt column

- messaging/Controllers/BundlesController.cs
Add missing message types to the bundles controller so they are labeled as "MOR" in the database
> Add alias to message types

- .github/workflows/update-swagger.yaml
Fixed the git committing process which was throwing errors when trying to commit and push without any changes to `gh-pages`
> Fixed swagger GitHub Actions Workflow

- messaging.tests/Integration/BundlesControllerTests.cs
- messaging.tests/Integration/SteveEndpointTests.cs
- messaging/Controllers/BundlesController.cs
Sets the source endpoint if it is missing from the submitted message. This will prevent extraction errors. Since the jurisdiction had to authenticate and can only submit to their endpoint, this is not a security risk to set the endpoint for them from a look up table.
~This PR is dependent on branch 471 getting merged into the vrdr-dotnet library so it can look up the endpoint by jurisdiction ID.~
The PR in the library was deleted, changing approach to return an error when source endpoint is missing
> Fill in missing source endpoint

- messaging.tests/Integration/BundlesControllerTests.cs
- messaging.tests/fixtures/json/CauseOfDeathCodingMsg.json
- messaging.tests/fixtures/json/ExtractionErrorMessage.json
- messaging.tests/messaging.tests.csproj
- messaging/Controllers/BundlesController.cs
Returns a 400 if the message type is an extraction error. Tells the user the message type is not supported by the API and to report the error manually
> Return 400 when an extraction error is sent

- .gitignore
- messaging/Controllers/BundlesController.cs
- messaging/Controllers/SteveController.cs
This PR improves speeds on the /Bundle GET endpoint with many records in the database. Previously, 100k records would take ~10 seconds, now 100k records take <0.5 seconds.
This was achieved by use `IQueryable` objects rather than `IEnumerables`.
> Improve /Bundle endpoint GET speeds.

- APIValidationChecks.md
- CHANGELOG.md
- messaging.tests/Integration/BundlesControllerTests.cs
- messaging.tests/fixtures/json/DeathRecordSubmissionMessageInvalidCertNo.json
- messaging.tests/messaging.tests.csproj
- messaging/Controllers/BundlesController.cs
- messaging/NVSSAPI/fsh-generated/resources/CapabilityStatement-NVSS-API-CS.json
- messaging/NVSSAPI/input/fsh/NVSSAPI_CapStmt.fsh
- messaging/Startup.cs
- messaging/messaging.csproj
This PR adds validation for the certificate number and the destination endpoint. The destination endpoint logic will be backwards compatible and compatible with the upcoming version of the library that will support a list of destination endpoints. The endpoints will be get and set as a comma separated list to support backwards compatibility. Therefore this PR is not blocked by the library update.
> Add cert no and destination validation

- messaging/Startup.cs
remove swagger for prod, thought we needed it for the security scan but we can point them to dev instead
> remove swagger for prod

- APIValidationChecks.md
- messaging.tests/Integration/BundlesControllerTests.cs
- messaging.tests/Integration/SteveEndpointTests.cs
- messaging/Controllers/BundlesController.cs
This PR adds a check to validate the jurisdiction ID in the message submission parameter resource against the jurisdiction ID in the URL endpoint parameters.
Supports Batch `/Bundles` which will return response bundle with BadRequest entries and `/Bundle` which will just return a BadRequest.
Had to update several old tests to conform with this new validation. Most just needed a message with the parameters resource in it, some had inconsistent jurisdiction IDs that needed updating.
> NVSS 484 - Validate Jurisdiction ID in message and URL param.

- README.md
- messaging.tests/Integration/BundlesControllerTests.cs
- messaging/Controllers/BundlesController.cs
- messaging/NVSSAPI/input/fsh/NVSSAPI_CapStmt.fsh
- messaging/Services/ConvertToIJEBackgroundWork.cs
This PR adds the ability to query by Business IDs when both a certificateNumber and deathYear are provided on the `/Bundle` endpoint. If not both are included, then it will act as the standard endpoint to get unretrieved messages by jurisdiction ID.
Endpoint parameter options are documented in the README.
Made updates to the fsh NVSS capability statement, worth double checking to make sure that's correct.
> Query by business ids

- APIValidationChecks.md
- README.md
- messaging/Controllers/BundlesController.cs
Updated docs to fix a few things
- fixed mention of the double queue in the README
- updated validation documentation to eventually give to STEVE team
- clarified in README the certificateNumber, and deathYear are only tested and approved for use with the backup endpoint, not through STEVE
- Added the new params to the pagination error response message
> Clean up documentation

- APIValidationChecks.md
- messaging.tests/Integration/BundlesControllerTests.cs
- messaging/Controllers/BundlesController.cs
This PR makes NCHS endpoint validation case insensitive.
It adds back the code reverted by:
- #72
- #71
> NCHS endpoint validation is now case insensitive

- messaging/Controllers/SteveCapStmtController.cs
- messaging/Services/ConvertToIJEBackgroundWork.cs
- messaging/Startup.cs
Remove dead code flagged in static analysis scan and add headers flagged by security scan.
> V1.1.0 preview19 scan fix

- messaging.tests/Integration/BundlesControllerTests.cs
- messaging.tests/fixtures/json/DeathRecordSubmissionMessagePST.json
- messaging.tests/messaging.tests.csproj
- messaging/Startup.cs
This pull request addresses an issue where the Newtonsoft JSON parser was silently altering datetimes of user submitted data to the timezone where the API is running, thus changing the local time that jurisdictions were providing and that NCHS expects into incorrect values. The pull request also includes a regression test that ensures the datetimes are not being altered.
> Fixes a bug caused by Newtonsoft JSON parser altering datetimes

- messaging/AppSettings.cs
- messaging/Startup.cs
- messaging/appsettings.Development.json
- messaging/appsettings.Test.json
- messaging/appsettings.json.sample
This enforces the guidance in the API README that payloads should not exceed 10MB. If jurisdictions have more messages to submit, they should submit multiple batches.
> add max payload size to app settings

- messaging.tests/Integration/BundlesControllerTests.cs
- messaging/Controllers/BundlesController.cs
- messaging/Controllers/CapStmtController.cs
Made a couple changes to address issues flagged in the security scan. The message parse exception handling can't have empty catch blocks and the stream reader for the capability statement was configured to have a maximum size.
> Read capability stream

- messaging.tests/Integration/BundlesControllerTests.cs
- messaging.tests/Integration/SteveEndpointTests.cs
- messaging/AppSettings.cs
- messaging/Controllers/BundlesController.cs
- messaging/Migrations/20250327181615_IGVersion.Designer.cs
- messaging/Migrations/20250327181615_IGVersion.cs
- messaging/Migrations/ApplicationDbContextModelSnapshot.cs
- messaging/Models/IncomingMessageItem.cs
- messaging/Models/OutgoingMessageItem.cs
- messaging/appsettings.Development.json
- messaging/appsettings.Test.json
This PR adds support for configuring IG Versions and update the URL param to use the PAYLOAD_VERSION format (BFDR_STU2_0) rather than the shorthand version (v2.0).
I did some iffy stuff to delete the old migration because it was causing some issues, so if that migration was applied locally you'll need to reset the database. Should be fine for the deploy since the migration was never applied there.
> 751 - Adds support for configuring IG versions

- .vscode/launch.json
- APIValidationChecks.md
- messaging.tests/Integration/BundlesControllerTests.cs
- messaging.tests/fixtures/json/DeathRecordSubmissionBlankString.json
- messaging.tests/fixtures/json/DeathRecordSubmissionNullValue.json
- messaging.tests/messaging.tests.csproj
- messaging/Controllers/BundlesController.cs
This PR includes:
- A minor refactor on how submitted bundles are handled:
- Bundles are initially parsed as generic JSON, just enough to tell if the bundle is a batch or message.
- Batches are split up and handled on a per entry basis. Each entry is treated as a distinct message. `InsertBatchMessage` and `ParseIncomingMessageItem` have been adjusted to handle the raw resource instead of the previously permissively parsed bundle.
- `ParseIncomingMessageItem` now does a strict parse on the message. If it's invalid FHIR, the issues are properly reported back to the submitter.
- Added tests for bundles with blank strings and null values.
- Updated launch.json to use net6.0 for debugging.
> 775 - Do strict FHIR parsing on bundles

- README.md
- messaging.tests/Integration/BundlesControllerTests.cs
- messaging/Controllers/BundlesController.cs
If any (or all) of the optional parameters are included in a GET request for responses, any matching responses will not be marked as retrieved.
> 773 - Don't mark as retrieved if params are included
