global.json, messaging.tests/messaging.tests.csproj, messaging/Controllers/BundlesController.cs, messaging/Migrations/20211203145846_AddMessageIdentificationInformation.Designer.cs, messaging/Startup.cs, messaging/appsettings.Development.json, messaging/messaging.csproj
This includes some useful commented out code allowing for the debugging of any strange request and response behavior that may arise.
=> Upgrade to dotnet core 6 and EntityFramework 6

messaging/Controllers/BundlesController.cs, messaging/Migrations/20220210214309_update-column-types.Designer.cs, messaging/Migrations/20220210214309_update-column-types.cs, messaging/Models/IncomingMessageItem.cs, messaging/Models/OutgoingMessageItem.cs
set event type and cert no to CHAR types length 3 and 6 respectively
=> Update column types

messaging/messaging.csproj
Use the latest VRDR Messaging library.
=> Bumped VRDR.Messaging version.

README.md, messaging/Controllers/BundlesController.cs, messaging/Controllers/SteveController.cs
Added debug level logs in the bundles controller and instructions in the README on how to turn debug logging on by setting the level in appsettings.json.
Moved the GET request into a try catch block so we can log any caught exceptions
=> Add debug logging in Bundles Controller

messaging/messaging.csproj
=> Update library to v4.0.0-preview6

messaging.tests/Integration/BundlesControllerTests.cs, messaging.tests/Integration/SteveEndpointTests.cs, messaging/Controllers/BundlesController.cs
Verify that the provided value for jurisdiction ID is valid.
=> NVSS-394 jurisdiction

DeploymentSteps.md
Add deployment steps to the project documentation
=> Add deployment steps to the documentation

README.md
This pull request adds instructions for how to do bulk submissions to the README.
=> Add instructions for bulk submission to README

CHANGELOG.md, README.md, messaging/NVSSAPI/fsh-generated/resources/CapabilityStatement-NVSS-API-CS.json, messaging/NVSSAPI/input/fsh/NVSSAPI_CapStmt.fsh
documentation updates for v1.1.0-preview5 release
=> Changelog for release

README.md, messaging.tests/Integration/BundlesControllerTests.cs, messaging.tests/Integration/SteveEndpointTests.cs, messaging/Controllers/BundlesController.cs, messaging/Controllers/CapStmtController.cs, messaging/Controllers/SteveCapStmtController.cs, messaging/Controllers/SteveController.cs, messaging/NVSSAPI/fsh-generated/resources/CapabilityStatement-NVSS-API-CS.json, messaging/NVSSAPI/input/fsh/NVSSAPI_CapStmt.fsh, messaging/appsettings.Development.json
In response to request made in Zulip to align with the FHIR spec
https://chat.fhir.org/#narrow/stream/179301-Death-on-FHIR/topic/Full.20FHIR.20Server.20Implementation 
Changed Bundles to Bundle in the documentation, supporting both for now so this doesn't break testing
Changed the CapabilityStatement endpoint to metadata see link below, unsure on how to support the mime type version and looking for feedback 
https://hl7.org/fhir/http.html#capabilities
=> Align with FHIR spec

messaging.tests/Integration/BundlesControllerTests.cs, messaging/Controllers/BundlesController.cs
This pull request updates the API to
1. Only display the "next" link if there are in fact more messages to retrieve
2. Correctly display the total number of records rather than the number of records being returned in the "total" field
=> Only show "next" link if needed and show correct results "total"

CHANGELOG.md, messaging/NVSSAPI/fsh-generated/resources/CapabilityStatement-NVSS-API-CS.json, messaging/NVSSAPI/input/fsh/NVSSAPI_CapStmt.fsh
increment version number for next release to deploy on the NCHS server
=> updates for new release

messaging/Controllers/BundlesController.cs
=> Send back error message not stack trace

CHANGELOG.md, messaging/NVSSAPI/fsh-generated/resources/CapabilityStatement-NVSS-API-CS.json, messaging/NVSSAPI/input/fsh/NVSSAPI_CapStmt.fsh, messaging/messaging.csproj
updated to latest library release, updated changelog and capability statement for new version
=> Update capability statement and changelog

APIValidationChecks.md, messaging.tests/Integration/BundlesControllerTests.cs, messaging.tests/Integration/SteveEndpointTests.cs, messaging/Controllers/BundlesController.cs
Catches a null cert and returns an http error response. Updated tests to account for the change. Also added a markdown file that documents the validation checks we do in the API so we can share with the STEVE team.
=> 480 catch null cert

APIValidationChecks.md, messaging/Controllers/BundlesController.cs
add missing logs on bad requests and update documentation
=> Add log messages

README.md
Clarify guidance on how pagination should be implemented in client side systems, recommend that _since only be used for testing purposes
=> Pagination documentation

CHANGELOG.md, messaging/NVSSAPI/fsh-generated/resources/CapabilityStatement-NVSS-API-CS.json, messaging/NVSSAPI/input/fsh/NVSSAPI_CapStmt.fsh, messaging/messaging.csproj
=> Update library version

APIValidationChecks.md
Reverts nightingaleproject/Reference-NCHS-API#68
=> Revert "Update APIValidationChecks.md"

messaging.tests/Integration/BundlesControllerTests.cs, messaging/Controllers/BundlesController.cs
Reverts nightingaleproject/Reference-NCHS-API#66
=> Revert "NVSS 509: Made destination endpoint validation case insensitive"

APIValidationChecks.md, messaging.tests/Integration/BundlesControllerTests.cs, messaging.tests/Integration/SteveEndpointTests.cs, messaging/Controllers/BundlesController.cs
Reverts nightingaleproject/Reference-NCHS-API#63
=> Revert "NVSS 484 - Validate Jurisdiction ID in message and URL param."

CHANGELOG.md, messaging/NVSSAPI/fsh-generated/resources/CapabilityStatement-NVSS-API-CS.json, messaging/NVSSAPI/input/fsh/NVSSAPI_CapStmt.fsh, messaging/messaging.csproj
includes the library fix to handle partial date issue for UT
=> Update to v4.1.1

CHANGELOG.md, messaging/NVSSAPI/fsh-generated/resources/CapabilityStatement-NVSS-API-CS.json, messaging/NVSSAPI/input/fsh/NVSSAPI_CapStmt.fsh, messaging/messaging.csproj
=> Update lib to 4.1.4

APIValidationChecks.md, README.md, messaging/Controllers/BundlesController.cs
Reverts nightingaleproject/Reference-NCHS-API#79
=> Revert "Clean up documentation"

README.md, messaging.tests/Integration/BundlesControllerTests.cs, messaging/Controllers/BundlesController.cs, messaging/NVSSAPI/input/fsh/NVSSAPI_CapStmt.fsh, messaging/Services/ConvertToIJEBackgroundWork.cs
Reverts nightingaleproject/Reference-NCHS-API#78
=> Revert "Query by business ids"

CHANGELOG.md, messaging/NVSSAPI/fsh-generated/resources/CapabilityStatement-NVSS-API-CS.json, messaging/NVSSAPI/input/fsh/NVSSAPI_CapStmt.fsh
Update version in capability statement and change log
=> Update version number

APIValidationChecks.md, CHANGELOG.md, README.md, messaging.tests/Integration/BundlesControllerTests.cs, messaging.tests/Integration/SteveEndpointTests.cs, messaging.tests/fixtures/json/DeathRecordSubmissionMessagePST.json, messaging/Controllers/BundlesController.cs, messaging/NVSSAPI/fsh-generated/resources/CapabilityStatement-NVSS-API-CS.json, messaging/NVSSAPI/input/fsh/NVSSAPI_CapStmt.fsh, messaging/Services/ConvertToIJEBackgroundWork.cs, messaging/messaging.csproj
restores the jurisdiction url validation, query by business id feature, and updates the validation documentation
=> 517 validation

DeploymentSteps.md
Updated the deployment documentation after walking through a deployment using the guide.
=> Updates to the deployment doc

CHANGELOG.md, messaging/NVSSAPI/fsh-generated/resources/CapabilityStatement-NVSS-API-CS.json, messaging/NVSSAPI/input/fsh/NVSSAPI_CapStmt.fsh, messaging/messaging.csproj
updates the library to 4.1.9 and bumps the api patch version
=> Update to 4.1.9

CHANGELOG.md, messaging.tests/Integration/BundlesControllerTests.cs, messaging/NVSSAPI/fsh-generated/resources/CapabilityStatement-NVSS-API-CS.json, messaging/NVSSAPI/input/fsh/NVSSAPI_CapStmt.fsh, messaging/messaging.csproj
Update the vrdr library version and add wait times to tests to address race conditions
=> V1.2.2 release

messaging/Controllers/BundlesController.cs
This PR fixes an issue where an error indicating that a BFDR message could not be parsed would be logged whenever given a VRDR message.
=> Fixed error log (677)

CHANGELOG.md, messaging/NVSSAPI/fsh-generated/resources/CapabilityStatement-NVSS-API-CS.json, messaging/NVSSAPI/fsh-generated/resources/ImplementationGuide-nvss.api.json, messaging/NVSSAPI/input/fsh/NVSSAPI_CapStmt.fsh, messaging/messaging.csproj
Bumb vrdr to 4.4.2 and update changelog for new release
=> Update changelog for new release

messaging.tests/Integration/BundlesControllerTests.cs, messaging.tests/fixtures/json/BatchSingleBirthMessage.json, messaging.tests/fixtures/json/BirthRecordSubmissionMessageInvalidCertNo.json, messaging.tests/fixtures/json/BirthRecordSubmissionMessageInvalidEventYear.json, messaging.tests/fixtures/json/BirthRecordUpdateMessage.json, messaging.tests/fixtures/json/DeathRecordSubmissionMessageInvalidEventYear.json, messaging.tests/messaging.tests.csproj, messaging/Controllers/BundlesController.cs, messaging/messaging.csproj
Use bfdr v1.0.0-preview.10 and vr v1.0.0-preview.5 which include message header validation
Add tests to confirm validation catches missing event years in the message header
=> 673 validate message header

messaging.tests/Integration/BundlesControllerTests.cs, messaging.tests/fixtures/json/FetalDeathRecordSubmissionMessage.json, messaging.tests/messaging.tests.csproj, messaging/Controllers/BundlesController.cs, messaging/Services/ConvertToIJEBackgroundWork.cs, messaging/messaging.csproj
This PR adds support for FetalDeath. It changes the BFDR endpoint to be specifically BFDR-BIRTH. The FetalDeath endpoint is BFDR-FETALDEATH.
=> feat(canary): 719 adds fetaldeath support

.github/dependabot.yml, messaging.tests/Integration/BundlesControllerTests.cs, messaging.tests/Integration/SteveEndpointTests.cs, messaging.tests/messaging.tests.csproj, messaging/messaging.csproj
- Added basic dependabot config for nuget based projects
- Updated to latest major versions of dependencies
- Address async void warning from xUnit update
=> 783 - Add basic dependabot config for nuget

DeploymentSteps.md
Revised documentation based on recent deployment experience.
=> 718 - Update Deployment Docs for Status UI
